### ISSUE TITLE
I didnot run it got errors

### ISSUE THREAD

**Issue by JigneshPatel04** [john-smilga/react-beach-resort-project#3]
![Capture](https://user-images.githubusercontent.com/7892462/70795977-1f5b5c80-1dc7-11ea-8037-816e2d9dbbc9.PNG)

**Comment by supplexcity** [comment]
make sure your .env.development file is outside src folder.

**Comment by JigneshPatel04** [comment]
Thanks for replied. I have no one file on that's . do you have any file? please share with me.
we got the error from contentful.js

const contentful = require("contentful");

export default contentful.createClient({
  space: process.env.REACT_APP_API_SPACE,
  accessToken: process.env.REACT_APP_ACCESS_TOKEN
});

**Comment by MZeeDev** [comment]
I'm also getting this error.

**Comment by MZeeDev** [comment]
> make sure your .env.development file is outside src folder.

Please share env file. thanks
